server:
  port: 8857
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/paymentSqlDb?createDatabaseIfNotExist=true
    driver: com.mysql.cj.jdbc.Driver
    jdbc: mysql://localhost:3306/database_name?enabledTLSProtocols=TLSv1.2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  application:
    name: payment-gateway

cloud:
  compatibility-verifier:
    enabled: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serverUrl:
      defaultZone: http://localhost:8761/eureka